// AUTO-GENERATED by scripts/gen-lessons-index.mjs — do not edit.
import type { Lesson } from "./types";
import L0 from "./foundation/f01-what-is-a-ppp.json";
import L1 from "./foundation/f02-not-a-ppp.json";
import L2 from "./foundation/f03-ppp-contract-types.json";
import L3 from "./foundation/f04-management-contracts-terminology.json";
import L4 from "./foundation/f05-why-use-ppps.json";
import L5 from "./foundation/f06-ppp-pitfalls.json";
import L6 from "./foundation/f07-project-structure.json";
import L7 from "./foundation/f08-project-finance.json";
import L8 from "./foundation/f09-co-financing-public-support.json";
import L9 from "./foundation/f10-project-failure.json";
import L10 from "./foundation/f11-framework-process-cycle.json";
import L11 from "./foundation/f12-glossary-essentials.json";
import L12 from "./preparation/p01-why-a-framework.json";
import L13 from "./preparation/p02-framework-scope-instruments.json";
import L14 from "./preparation/p03-defining-ppp-process.json";
import L15 from "./preparation/p04-institutional-roles.json";
import L16 from "./preparation/p05-fiscal-commitments.json";
import L17 from "./preparation/p06-oversight.json";
import L18 from "./preparation/p07-identifying-projects.json";
import L19 from "./preparation/p08-economic-soundness.json";
import L20 from "./preparation/p09-ppp-screening.json";
import L21 from "./preparation/p10-appraisal-scope-structure.json";
import L22 from "./preparation/p11-financial-model.json";
import L23 from "./preparation/p12-commercial-feasibility.json";
import L24 from "./preparation/p13-economic-fiscal-feasibility.json";
import L25 from "./preparation/p14-vfm-procurement-strategy.json";
import L26 from "./preparation/p15-financial-structuring.json";
import L27 from "./preparation/p16-revenue-payment-mechanisms.json";
import L28 from "./preparation/p17-risk-allocation.json";
import L29 from "./preparation/p18-risk-events-contract.json";
import L30 from "./execution/e01-structuring-tasks-marketing.json";
import L31 from "./execution/e02-qualification-rfq.json";
import L32 from "./execution/e03-rfp-evaluation-criteria.json";
import L33 from "./execution/e04-commercial-terms-1.json";
import L34 from "./execution/e05-contract-provisions-2.json";
import L35 from "./execution/e06-tender-launch-bid-stage.json";
import L36 from "./execution/e07-qualification-dialogue-evaluation.json";
import L37 from "./execution/e08-award-financial-close.json";
import L38 from "./execution/e09-contract-management-framework.json";
import L39 from "./execution/e10-construction-monitoring.json";
import L40 from "./execution/e11-construction-change-claims.json";
import L41 from "./execution/e12-operations-monitoring.json";
import L42 from "./execution/e13-finances-regulation-fiscal.json";
import L43 from "./execution/e14-termination-handback.json";

export const LESSONS: Record<"foundation" | "preparation" | "execution", Lesson[]> = {
  foundation: [L0, L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11] as Lesson[],
  preparation: [L12, L13, L14, L15, L16, L17, L18, L19, L20, L21, L22, L23, L24, L25, L26, L27, L28, L29] as Lesson[],
  execution: [L30, L31, L32, L33, L34, L35, L36, L37, L38, L39, L40, L41, L42, L43] as Lesson[],
};
